FROM registry.redhat.io/ubi9/httpd-24

# Copy application sources
COPY app-src/*.html /var/www/html/
COPY app-src/images /var/www/html/images

# The run script uses standard ways to run the application
CMD run-httpd

