#!/bin/bashrc
echo "TEAM_NAME=$TEAM_NAME"
echo "USER_NAME=$USER_NAME"
echo "PASSWORD=$password"
echo "CLUSTER_DOMAIN=$CLUSTER_DOMAIN"
echo "GIT_SERVER=$GIT_SERVER"
echo "GITLAB_USER=$GITLAB_USER"
echo "GITLAB_PAT=$GITLAB_PAT"